language: python
python:
- '3.7'
install:
- pip3 install -r requirements.txt
script:
- python -m unittest discover
deploy:
  provider: heroku
  api_key:
    secure: zIuscWLzNQVu4pRdtnaPihZHjEcp2PtVldJFLmeWaiT1SHSSUJ/iBdQyEksD+NIwXN9Ym80L1WMtARQMZPW9SCgMEocH9cqae3MsQ2NHgWjz4z+Ycfjnf+1jYfabhLbB6wMd197DaznfdDvJGcYj1PagKMIvNfwmTU9ppXoEgxtTADHafOnW/mbAfYyaRPHW9AOihtZpYCnWSNFnePzSNogA6zCLv4CeVSPf9ejQXPsqAPg/zkZPYXGYCWp+ZBoS5JLEYvi4V/0hG39DDbMYheUBlW4sL6fKJgjf0H10AxGxrXv8v7F6Za/SLlBmTsbrhaf5kg8gSDy8ClH/vffzeDNrWEdBRMAbTKcy5l2kuxSwLeOpL7DI0LFBQaKa5CULgsmfuQlUoWVP3Z5mJzwWm5+XyVz3uAsj1F7oD1ktq54wJIqShfz8g1K0x5PTdcCLnlvAZRsZ9EablCdLB7hXpVrGh7T6suC8zfLPdQJl/bYg3C92XTXa8hPHj+c696rv5SoKgMA4gZq/L3Pw7mAaWebpTIYmrRQvAm2jvzgCja5zh2/+xQuPs2jZp6xqQ1r15kb4nQX+x1UTy198Rn5sOmvv99Mgwcio3G7q7fPushQb4aN2M9QLsd3prJc+uDtsUfaZKp+ArdJWy1P9GE1XoptAaRBHkjoemXpHHlWEUrw=
  app: cisc3140-assignment3