language: python
python:
- '3.7'
install:
- pip3 install -r requirements.txt
script:
- python -m unittest discover
deploy:
  provider: heroku
  api_key:
    secure: MtjPaMEPesJrlPyQ3DGN8mKF2YYgyACvK970aokY2SroHZfo86yWxVIHhjC+4LFzIr6YuwT55wSFhLZkgrqE8jueZaJVVpsSGsjn/PmT/GGYzGGhjEg7xN5DHDs0H5E0w6omPCW+GtUGGgtFWmsyqGX+Z5degAM95OAiDAADnab9IRmZ+dKOBNUnXkb5us4DVukbBdpPlhv/c+N121nBCL5EyRIA3TSPu+t1YAonVjvjWvdsnCdtWnP8DWjqsw8/vtmOIA156wKRauctQKyVyR0UQNlRvs8PClawlfRbSPGAlBiOqT0PIZsk727jZuH5MLoUMXdnACGVlMXELy0rW2meEwGI+u7ChQC0/6RE/Iu7QwIg8ncWq1XyHebvRMdXJ0FJLYUhJZ+pfRgrDIb4Ta8ipe8xHkfnxBmXq9h2EUhwVtpPi7WizG6qpD402Mel6SytnPe6RXG6426K2Gn/cXGKEHGG6COFNEVxejR487vGDCeA8x2EtOygeX/mND8YpOSaorI0jxQv9eDM/VclgpqRArpX2P+est/eJPQ7yfeaD6KYYkpUU6797nL5hasKRUxhYRR0ZbcA93GrWQczBwWmWUjw8XwoyDvaiocsEVrBuOvS9b+WmZCu7qqCD692pCKmf4xOugcLTQeNCNydfrBqgCcVHG6vMpuFrhw6ZNc=
  app: f
