language: python
python: '3.7'
install: pip3 install -r requirements.txt
script: python testpy.py
deploy:
  provider: heroku
  api_key:
    secure: zHc+4gThqhe0HjwpEagPzAjR0CbN/tDJ7mhtHaaGkelmuGwd4lTjnMV5ZfAg3UXGNr8wLXqz81u6M0X5xaauVxd/3iJCvu9ismcQi8CpdSDl5QYfoDZ9hapwZsmLilLyMWibte/c/lWCSbCzahfFLQWiLaG+wZD5ENPtgOtTmMUuwdVjMkxHI0DUHzhHolBAhQtFvKSLT1dAR/Ie8FuCjEbVsOz/9ZNgNBpevT0ryFOGHsI2OByjt/+BKdgMyGriFD0pqE4pjYF1PmCSOK2RaxUZ4nLZGHfJIfTxNkeRyW9iwLkHF/0P4ItPnYQJjHPlQw19U510cCb0RUqFI5hUMvKOaJ2a9v3JHrfm1aYkbhBH94RVY8yjF5CYHkcdABLUKGhNC8zpNZHtBiSgB6heziDMcjotMALohv8N0rbPfWt9m0eIY0IOKUE9jCD0aIBx8qJVYj07EOukA/XS2DALkKgtaoQEFESu4xvzkNg8iSuY5wOReJR7c9b1XdLSCOT1iOPZ7k7wU8AA9znpmT/ZwWBggYVEZvla266S+GYb654iBErvVq/edbRKVUq6AeUOnD8O8O8F7GEAXGIi6yIMEQmTkaKOQnIKRr4k3xYHKEmOyPbtQ8vKnGb8vAOqZKYoRZtx8KyCAcbQjLdqcFmlym4kh26fUGpWp+STcdT8mdk=
  app: travis-heroku-deployment
