language: python
python:
- '3.7'
install:
- pip3 install -r requirements.txt
script:
- python -m unittest discover
deploy:
  matrix:
  - provider: heroku
  api_key:
    secure: EjtEnO8WiqUMR9JqghjQ8MfhycGHYPrx0rIONrN7QnuTMnk4YHU+72UwTe/Nu2ImNYSEck4GOtQMc4zzpyG84amTULDiuqNSO97EJEdLQj7Ms8qRnPeP2Wdvvltm0smPKA7wdid5w70Y69lF/Dgk2UN3wd9whsUJuivI8DHx9VIRjTcLr+YjzouhOF+ifDlNSrdcFWEOTWhrMCDfCnosp04jWxAOE2dJ8KZl/E+BstFi373nSj3l9KmhEBo4ol2UdG2aiDc+2A8341ip7AjUiUUQghNtjfyT0Bmj/O0uXciFpklY7m1ckdGFR5R9rL1MTDUNxBBhMrs+QyfeXtv8RzSOnkE9yyD8uXMTl7Uukg9/Uewdb1s2jXFluzE6hYqByoeptH+IHrZ23WuoiLV0BRg6eUqTE/GR6yrJbb1FgYOh//pw+v7fwnfVWhqwZIFRExuySWanzD8scjP058BES7WXDhP5Zza2wYIOTE88JdkVq/+4LarOXfVxV2sKVXgEJZMXwax5HMNMoswcjdTdWnp4R+5VZ7Xn+j2RrIxo2xXr2PCCPBIRrl4JgXYMlK/RzgMCzEOpVdcvAdBOqHG9oF3hhJ3tmNyGLXPvjMhTfHbGcFBBOSU1iiNW6EviRBbXL7E2dtQ2lpwDAAwsDtW8ZELooMhaBVIUjvMLc4PYzQM=
