language: python
python:
- '3.7'
install:
- pip3 install -r requirements.txt
script:
- python -m unittest discover
deploy:
  provider: heroku
  api_key:
    secure: JmVV2yyLj2RrLnu4B44WIE7ZYnEEHbAtkjoVxGGLVU8fOy+k/KxBOZ4gAC1g7RT797Qua3KMRTEh1/dN65l59k7kGx00i2n8ej9JN6vYTo1bTxwGRJnb6CTHZ4l10PzKaLuMbuCvvQjFtwVjSAXbW/3b5Mf9IIeM4TlHrMAAOjuq+xhNQgAFaWEDhOKSz3a2/pjI99uTdU1PcsNFaP0cB7sUM4SzYvKCWIWoqv6okpIqOuNvme/CVEeNLAmVsqJF7/I9iC9BL0ygz1dIlwyLkkZXtsevHclgDY8Lpdd6xMVanLnT/EEQ1Nrvh90LU65VcgMNCw5zQD+XirZ3RoRCb0bxa2hWcplachHvRs4KW3Wk4cALa7aUbZCRWbw/EcmGBkBic84g5kx+/ibsL5s+ovG31n4Qx9nGKNW0lyRC5iRHxbJUj83HwNPX1Ty1cjprjTNNrfslJmk29LLsTKZfDtniZJUtzpUfMAtAQQ8OzqlGVclDfJXLrrqFuC6MkCsyC7nxxLodMWkbKmZNEmvx3m6LS4aM/eZOUjHhigBYBBM6Jl0C+0QtJNzJTHlHZKcpWomUu1ueDHRQxaWW+CHWzaAKvw7oTkVCt66nOdcpiGkRuvfb+0pDiDOXBGwLxWS02wJwtp0/BbPpSy0UdbZbCLhmZWP4i2bjylLeuodEw+A=
