language: python
python:
- '3.7'
install:
- pip3 install -r requirements.txt
script:
- python -m unittest discover
deploy:
  provider: heroku
  api_key:
    secure: 2Qcj4oWKrXvuT/bH/PM1jtz8wpkeoN/3R0CmBAHb6tmmn9XPWbOEiaJk3fLjK9t71JI6Hy9K0dqNXLar5tEz4Jo4O2sCDpLDsuE3kw+ohWLL1LVRrqYo64JDICsUTyg9LTWfEs5Q2YDmnD4h8MuWXYhIFQ2xlIK0nMsoQjUW4bgVo5TTqMD0DKJUQ7KF+OLUIjgl+4puIwTJun1LRC27it8E3dXHvHSCYeA3oRe/cr0nUewN+QfEnVYgCuEGtpcjnJFnemIv6g68P7KpomO70tRBMoUE/1w/j3MDok35GLsBkVXEp/O3CG74TQwILMhRd1pQsw0JQgYCCYqUghaxQhgvHNZgCJxk5ZHWW1uPwkMLz331iUzvjO9Y9CvdJsdqx9MB1aQ+OXsBnMmY/EPrMI9tXdit2kVyTnkyNlIHZbFh4jQrxXhIrdXZGqMDdIBeTjCd62ogaqyKx5KEfzA0fIOvS9n17vALq5j8dk9qu/Q+GhgHMxEu46M6nvm5Ia1aIRr6SscpaZt1PUx4GIu+9ueg4jZH/gtcNz4VnAcF8fsgDPwpsMb46slj+4Tcf45GymY6/1xjPlh1kupuebzOr8lQUsiz9KWjnM2cDAmMtnvQgH5BR+wfsVtoiI8mmOnZumMLY7DGf0sJScLUqSBNeyB5BlrVeAU361+tlJo2Oj8=
  app: f
