language: python
python:
- '3.7'
install:
- pip3 install -r requirements.txt
script:
- python -m unittest discover
deploy:
  provider: heroku
  api_key:
    secure: WSaTgpWiz8G11JWfBmDcouGw3qT8tjAhg2Irggm7gg8BW+0Wau3s+PyZPkZuPeMvhufrz/DMnlzzHmuxsOPdGLitvxXiX0hTDYIhCw61Dc0Pz/V0wa2jG0+RGU/9UInUQzpA092SNcEunc66y08WD2A0bnBe9mhNwgX+9O2YRlPMZgZCuh4oMNGcNHunVVj1nZvlCMXgUso+RCbQH0wnNYZRmd9p+ldFzLztGOlVuc6ohM9xBO118+meT5CVaCP1arquZby/PqkX2emYj2urOERuC7QtdstiomZlszuH4Pfg00N6slIOvsEXj7YZx142QR4/MmAHHH4fCUDs93yfM/AYWdlCcF2Y7PWIdI8h6SiNYrvU+SFmkFSzHohxX1N3O/XN8goT1RX0180dCggP157HoG6DOkpiT5gUz3853ZTtrlFsqEKLWffcHoKbtksCYNmoywFQMrdkE/5lQln5+e4A1e2W/sNgOSLLs0GcD2TMuJe+HdTBJD1LHrhwMwehjuZlxVxvXhfX/52A+e38XQNcXGY1MDc1N7oL6vg21+xigGvMJtpDIIA0jWf2fA8niRQ0xuKNfsFEDzoLSx6swYsvZqsyE1J+kEqbaQwmmsZbbyrHR3aCFc/Uvw8CnjuHykbmlIU9vwu3YDmEHTvrMB9cYqr1RkNY9DiDxO2zydQ=
